[build]
  base    = "apps/web"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS    = "--legacy-peer-deps"
  NEXT_PUBLIC_SITE_URL = "https://endearing-taffy-91a2c6.netlify.app"
  NEXT_PUBLIC_API_URL = "https://local-business-listing-directory-production.up.railway.app/api/v1"
