/** Listing Questions doc — canonical seed for business_questions table. */
export const BUSINESS_QUESTIONS_SEED: Array<{
    category: string;
    question: string;
    options: string[];
    order: number;
}> = [
    {
        category: 'Business Type',
        question: 'Where does your business operate?',
        options: [
            'Physical Location',
            'Home-Based Business',
            'Online / Digital Only',
            'On-Site at Client Location',
            'Mobile Unit',
        ],
        order: 1,
    },
    {
        category: 'Core Business Nature',
        question: 'What does your business primarily do?',
        options: [
            'We sell physical products',
            'We sell digital products',
            'We provide in-person services',
            'We provide online or remote services',
            'We offer delivery to customers',
            'We manufacture goods',
            'We import and distribute',
            'We provide consulting or advisory',
            'We operate a marketplace',
            'We rent or lease assets',
        ],
        order: 2,
    },
    {
        category: 'Operational Structure',
        question: 'How does your business operate?',
        options: [
            'Manufacturer',
            'Assembler',
            'Fabricator',
            'Farmer / Agricultural Producer',
            'Extractor / Mining',
            'OEM (Original Equipment Manufacturer)',
            'Private Label Producer',
            'Garment / Textile Factory',
            'Retailer',
            'Wholesaler',
            'Distributor',
            'Importer',
            'Exporter',
            'Dealer / Authorised Seller',
            'Reseller',
            'Franchise',
            'Broker',
            'Agent / Representative',
            'Auctioneer',
            'Commission-Based Facilitator',
            'Marketplace Operator',
            'Franchisee',
            'Consulting / Advisory',
            'Installation',
            'Repair & Maintenance',
            'Design',
            'Training / Education',
            'Technical Support',
            'Operations Management',
            'Cleaning / Hygiene',
            'Security Services',
            'Logistics / Transport',
            'Healthcare / Medical',
            'Legal / Compliance',
            'Individual / Freelancer',
            'Partnership',
            'Private Company',
            'Public Company',
            'Government Entity',
            'Nonprofit / NGO',
            'Cooperative',
            'Other',
        ],
        order: 3,
    },
    {
        category: 'Who Do You Serve',
        question: 'Who are your primary customers?',
        options: [
            'B2C - Individual Consumers',
            'B2B - Other Businesses',
            'B2G - Government & Public Sector',
            'D2C - Direct to Consumer',
            'Wholesale Buyers',
            'International Clients',
            'Local Community',
            'Students / Education',
            'Healthcare Patients',
            'Property Owners / Tenants',
        ],
        order: 4,
    },
    {
        category: 'Contact Details',
        question: 'How can customers reach you?',
        options: ['Primary Phone', 'WhatsApp Number', 'Additional Phone Numbers (up to 5 on paid plan)', 'Business Email', 'Website URL'],
        order: 5,
    },
    {
        category: 'Business Hours',
        question: 'When are you open?',
        options: [
            'Monday Open',
            'Tuesday Open',
            'Wednesday Open',
            'Thursday Open',
            'Friday Open',
            'Saturday Open',
            'Sunday Open',
            'Open 24/7',
        ],
        order: 6,
    },
    {
        category: 'Business Description',
        question: 'Tell customers about your business',
        options: ['Business Description Added', 'Business Languages Added'],
        order: 7,
    },
    {
        category: 'Experience & Team',
        question: 'Tell us about your business maturity and team size',
        options: [
            'Year Established Added',
            'Just Me (Solo)',
            '2-5 Employees',
            '6-10 Employees',
            '11-25 Employees',
            '26-50 Employees',
            '51-100 Employees',
            '101-250 Employees',
            '251-500 Employees',
            '501-1,000 Employees',
            '1,000+ Employees',
            'Prefer not to say',
        ],
        order: 8,
    },
    {
        category: 'Website & Social Media',
        question: 'Where else can customers find you online?',
        options: ['Website', 'Facebook', 'Instagram', 'YouTube', 'LinkedIn', 'TikTok', 'X / Twitter', 'Pinterest', 'Snapchat'],
        order: 9,
    },
    {
        category: 'Keywords',
        question: 'Add keywords that describe your business',
        options: [
            'Local Service',
            'Professional',
            'Trusted',
            'Affordable',
            'Emergency',
            'Premium',
            'Family Friendly',
            'Fast Response',
            'Certified',
            '24/7',
        ],
        order: 10,
    },
    {
        category: 'FAQs',
        question: 'Add FAQs to help customers quickly',
        options: [
            'Pricing FAQ Added',
            'Service Area FAQ Added',
            'Opening Hours FAQ Added',
            'Appointment FAQ Added',
            'Payment Methods FAQ Added',
        ],
        order: 11,
    },
    {
        category: 'Logo & Cover Image',
        question: 'Upload profile media for your business',
        options: ['Logo (Recommended 400x400)', 'Cover Image (Recommended 1200x400)', 'Gallery Images Added', 'Album Grouping Enabled'],
        order: 12,
    },
    {
        category: 'Amenities & Facilities',
        question: 'What does your location offer?',
        options: [
            'Physical Location',
            'Online Business',
            'Mobile / Home Service',
            'Delivery Available',
            'Online Consultation',
            'Emergency Service',
            '24/7 Open',
            'Appointment Only',
            'Free Wi-Fi',
            'Parking Available',
            'Air Conditioned',
            'Waiting Area',
            'Wheelchair Accessible',
            'Elevator / Lift',
            'Kids Area',
            'Pet Friendly',
            'Female Staff Available',
            'Male Staff Available',
            'Cash Accepted',
            'Card Accepted',
            'Bank Transfer',
            'Mobile Wallet',
            'Online Payment',
        ],
        order: 13,
    },
    {
        category: 'Industry Sub-Type',
        question: 'Does your business fall into specialised sectors?',
        options: [
            'Factory',
            'Manufacturing Unit',
            'Industrial Supplier',
            'Packaging Company',
            'Printing Press',
            'Textile Mill',
            'Garment Factory',
            'Warehouse',
            'Cold Storage',
            'Wholesale Market / Mandi',
            'Export House',
            'Import Clearance Agent',
            'Seed Store',
            'Fertilizer Store',
            'Pesticide Shop',
            'Dairy Farm',
            'Poultry Farm',
            'Cattle Farm',
            'Tractor Dealer',
            'Agricultural Equipment',
            'Grain Market',
            'Livestock Market',
            'Irrigation Supplies',
            'Organic Farm',
        ],
        order: 14,
    },
    {
        category: 'Business Opportunities & Expansion',
        question: 'Do you offer expansion or partnership opportunities?',
        options: [
            'Franchise Opportunities',
            'Dealers / Resellers Needed',
            'Importer / Exporter',
            'Local Service Area',
            'National Service Area',
            'International Service Area',
        ],
        order: 15,
    },
    {
        category: 'Map Confirmation',
        question: 'Confirm your location on map',
        options: ['Pin Confirmed'],
        order: 16,
    },
];
